### ISSUE TITLE
Rename location to poi

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-app#2391]
**Is your feature request related to a problem? Please describe.**
We are using different naming in the app sometimes "pois" and sometimes "location". Since this is troubling lot of confusion we should unify this.
Check occurences where the naming does not match the description below, and adjust.

**Describe the solution you'd like**
- "poi" naming should be used for everything that is related to pois
- "location" naming should be only used for user position
- exception: "location" as a naming in the url-slug for pois should stay "location"

**Comment by steffenkleinle** [comment]
Did we discuss this? Actually I think the only place where we are naming this "location" is in the url slug and since #2380 in translations. However, we are using the wording in a few other places as well (as a synonym to city, for the place an event takes place, geolocation aka user position, feature locations, ...). So maybe we could discuss first what we actually want to rename.

**Comment by steffenkleinle** [comment]
But tbh I think I would just close the issue until we see a need/someone gets confused.
