### ISSUE TITLE
Add codeclimate to CI

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2466]
**Is your feature request related to a problem? Please describe.**
Add codeclimate to commit workflow, to remind us to write tests and to see how test coverage is affected by a PR.

**Comment by sarahsporck** [comment]
Does codeclimate cost sth? How is the backend is doing it currently? @timobrembeck @ulliholtgrave

**Comment by timobrembeck** [comment]
No, it's completely free for open source repositories.
I also don't think there are a lots of privacy concerns involved, but I didn't read the whole privacy policy, so not sure what data they're storing and evaluating exactly :sweat_smile:

**Comment by timobrembeck** [comment]
One cool thing about it is that it plays very nicely with [CircleCI's parallel tests](https://circleci.com/docs/parallelism-faster-jobs/), because its test reporter can join multiple partial coverage reports into one unified coverage report:

https://docs.codeclimate.com/docs/configuring-test-coverage#parallel-tests
