### ISSUE TITLE
Reorder the icons in the header

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2468]
**Is your feature request related to a problem? Please describe.**
Reorder the header/navigation items as follows:

1. local information
2. map with locations
3. news
4. events 

Keep in mind that on native only 2.-4. exist at the moment.

**Comment by steffenkleinle** [comment]
Personal opinion: An issue like this should not be in our github issues but rather in a personal TODO list. There is nothing we can do about this atm and perhaps we don't even have to do anything if the current order is perfectly fine. This feels more like a blocker for a possible future issue. What do you think? Other opinions?

**Comment by ztefanie** [comment]
I think it is good to have it in the backlog, so the whole team has an eye on it.

**Comment by dkehne** [comment]
From a network meeting with the municipalities we got the suggestion to reorder maps before news and events. Could be implement that or do we need more investigations from a user perspective?

**Comment by steffenkleinle** [comment]
@dkehne should this be implemented now? I.e. change the order to maps > news > events?

**Comment by dkehne** [comment]
@juliawohlhueter @clarabracklo was there any more evidence/feedback from the user group on that topic that is in contradicton to the newly suggested order?

**Comment by hauf-toni** [comment]
@steffenkleinle @dkehne @clarabracklo I think thinking about the order is super useful and important. We should choose a basis for our evaluation that we all find meaningful – unfortunately, isolated feedback has little to no statistical relevance. I would suggest that we should base our prioritization **primarily on our 🎯 impact goals** (and also best practice, but that's the obvious thing to do anyway).

____

This would be my suggestion:

1. local information
2. map with locations
3. news
4. events

**Local information** in first place, because: the central impact objective is to provide target group-specific information, to facilitate orientation in everyday life and to ensure access to existing information. This contains valuable content on integration and making everyday life easier, which is aligned with our most important impact objectives (access to and perception of information).

**Map:** provides visual and quick orientation, supports transparency and quick access to relevant information, possibility to find important places and services in a targeted manner.

**News:** Current information and news often of less urgency, but helps to participate in community life and keep up to date with current events. do not contribute directly to orientation, but can strengthen a sense of participation.

**Events**: last, as information can be more of an “add-on”: important aspect of integration + promotes networking, but rather subordinate in the context of user-centered design, as information and orientation are given higher priority.

_____

💬 Feel free to leave some feedback, I appreciate it!

**Comment by steffenkleinle** [comment]
@hauf-toni thanks for giving this additional thoughts, I think this makes a lot of sense. :green_heart:

**Comment by clarabracklo** [comment]
Might not be relevant anymore but to answer @dkehne question: There has not been any feedback/observations about this specifically.
