### ISSUE TITLE
Merge Feedback and FeedbackContainer

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-app#2524]
**Is your feature request related to a problem? Please describe.**
@steffenkleinle wrote in https://github.com/digitalfabrik/integreat-app/pull/2472: 

"IMO Feedback and FeedbackContainer should be merged (both native and web) because we are just passing a lot of props between the two components without any real separation of concerns from a logical point of view. Common logic between web and native could be moved to the api client/endpoint. What do you think?"

I agree :)

### Test information

Check if sending feedback in different variations and form different routes still works on both native and web.

**Comment by ztefanie** [comment]
I disagree. 
There is a separation of concerns.
Feedback is for rendering and all the visual stuff (all the styled components live there)
and FeedbackContainer is for the logical stuff.
In the tests it becomes really visisble, FeedbackContainer tests are `function xy should have been called...` and so on, whereas in Feedback all the tests are just `button should be disabled`, `correct text should be displayed`.

I think this two files show really good, how it is possible to split up components and how to realize single responsibly principle in frontend components easily. If we change something, we should more often split up components than merge these two into one.

**Comment by steffenkleinle** [comment]
> I disagree. There is a separation of concerns. Feedback is for rendering and all the visual stuff (all the styled components live there) and FeedbackContainer is for the logical stuff. In the tests it becomes really visisble, FeedbackContainer tests are `function xy should have been called...` and so on, whereas in Feedback all the tests are just `button should be disabled`, `correct text should be displayed`.
> 
> I think this two files show really good, how it is possible to split up components and how to realize single responsibly principle in frontend components easily. If we change something, we should more often split up components than merge these two into one.

I agree that just merging the two files is not a good idea because it becomes to big. However, I don't think the current way of splitting is a good one. First of all, things that are duplicated in native and web should be moved to the api-client which already reduces the size of the FeedbackContainer quite a bit. Second, at least in my opinion, UI should go normally in smaller modular components rather than in one big `Feedback` file which has all styled components. Instead, There should be separate smaller components like `Note`, `FeedbackButtons`, `TextInput` and so on. My main problem at the moment is that ALL the UI lives in ONE component (Feedback) and all the props are just passed down do that one component. And if we have those smaller visual components, we can a) reuse them in other places and b) just use them directly in `FeedbackContainer` because there is not that much need for additional styled components anymore.

**Comment by ztefanie** [comment]
Decision from grooming: We want to move shared stuff to api-client and split up Feedback into different components. (as @steffenkleinle suggested)
It is up to the assignee if the FeedbackContainer is still needed.
