### ISSUE TITLE
City list too long

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-app#2534]
**Is your feature request related to a problem? Please describe.**
As a user I want to easily select my city/region such that I can find the right information for myself. At the moment, the list becomes longer and longer and it gets therefore harder to find the right city (especially for city vs district..).

We should think about ways to make it easier for users to select the right city. Perhaps a simple list is not the right tool anymore.

**Comment by sarahsporck** [comment]
I guess a map could be a valid solution. Although, personally, I don't think the list is becoming too long.

**Comment by steffenkleinle** [comment]
I guess we would have to research that a bit more, apparently this was feedback from a target group meeting/workshop. Personally I also think the list with a search field is enough atm. But perhaps we still find easy to implement ideas?

**Comment by nikolahoff** [comment]
@steffenkleinle is this needed for the menu item "change location"? I also think a search field on top would be a good solution.

**Comment by steffenkleinle** [comment]
This is from a target group meeting. Maybe @dkehne can shed some more light on the need here.

@nikolahoff yes, I think it was specifically for the "change location" list even though there already is a search field.

**Comment by nikolahoff** [comment]
@dkehne can you give more information? What was the problem with the list? Couldn't they find the right city with the search?

**Comment by dkehne** [comment]
@nikolahoff i just forwared the feedback from one of the participants from one focus group. without more research it is hard to tell. I will forward the task back to the target group research team.

**Comment by clarabracklo** [comment]
I hope I can shed some light on this topic: 

We have received this feedback at a target group workshop in Munich. It was mentioned twice there. The users felt overwhelmed by the list of cities when they opened the app and suggested that rather than displaying a long list that is actually not used (they are not interested in seeing cities they don´t live in) they would rather have a more simple design with just a question like "Where do you live?" and than the nearest city available for example. The search field was not standing out to them and they only found it when we pointed to it. 

I have also checked other interviews we did this year and it this problem has not come up anywhere else. However this might be due to the format of the interviews where the interviewed people already used Integreat for longer, while the people in the workshop in Munich were first-time-Integreat-users.
