### ISSUE TITLE
Introduce constants for magic numbers

### ISSUE THREAD

**Issue by ztefanie** [digitalfabrik/integreat-app#2539]
**Is your feature request related to a problem? Please describe.**
Check all occurences of magic numbers (where the no-magic-numbers linting rule is disabled) and move the magic number to a well named constant and remove disable linting comment

**Comment by sarahsporck** [comment]
Since I [disabled the rule for objects](https://eslint.org/docs/latest/rules/no-magic-numbers#detectobjects) (as there the name is given by the object itself) there are only 4 occurences of this rule left (3 in webpack config, which I couldn't really get rid of and one in iframe.js which is technically external code). Do you think we can close this ticket?

**Comment by ztefanie** [comment]
@sarahsporck fine for me
