### ISSUE TITLE
Feedback functionality too hard to find and less used

### ISSUE THREAD

**Issue by clarabracklo** [digitalfabrik/integreat-app#2548]
I have received the feedback from Munich that since the new design of the feedback functionality no more feedback has been send to them whereas before they received 2 a week. This could be because the option of giving feedback is not as visible anymore without the smileys in the footer. I have also observed that users in user testings have a hard time finding the feedback functionality by themselves. 

Needs to be discussed and maybe checked with other municipalities. 

------------------------------------------------------------------------------------

Edit 23.9.24:
We will for now only change things in the web app, not the native one. There is currently one feedback button in the sidebar (footer on web mobile), we will change that to the two smileys saying useful and not useful that each open the feedback overlay with the pressed button being selected.

The design is here: https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=3708-16025&node-type=frame&t=NnheR3Z60BO01kgM-0

**Comment by hauf-toni** [comment]
as discussed with Martin, it might be useful to re-evaluate the visibility of the feedback function. possible solutions could be to explicitly point out the function in the intro slides and encourage users to use it. an assessment by the service team would certainly be helpful here.

**Comment by clarabracklo** [comment]
I think adding this to the intro slides could be helpful however I have observed that most people just skip through the slides and even if they read them they might forget about the feedback from the time they first start the up until the time they want to give feedback?

**Comment by steffenkleinle** [comment]
The easiest and most sure way to get users to send feedback would be to display a footer on every page again with feedback.

I am a little surprised anyway that its that much less feedback than before we because we only moved it to the overflow menu on native, on web the feedback button should still be shown below every page. The only change there was that we removed the two smileys and now use a comment icon. Maybe that is also not clear enough?

**Comment by steffenkleinle** [comment]
The easiest and most sure way to get users to send feedback would be to display a footer on every page again with feedback.

I am a little surprised anyway that its that much less feedback than before we because we only moved it to the overflow menu on native, on web the feedback button should still be shown below every page. The only change there was that we removed the two smileys and now use a comment icon. Maybe that is also not clear enough?

**Comment by dkehne** [comment]
After we have received the same feedback again at Kommunenumfrage we should discuss on the next conference. For me personally it feels like as we have hidden the feedback function on app.

**Comment by clarabracklo** [comment]
Just fyi: We have also gotten the same feedback again from Kreis Viersen.

**Comment by steffenkleinle** [comment]
> Maybe we can implement the feedback smileys again in the footer and see if the feedback is used again? It would be interesting to know if the feedback only decreased for mobile users as it is still visible on desktop.

@dkehne @svenseeberg do we have/can we calculate numbers for that? I.e. we'd need for numbers:
* Number of feedbacks WEB between 2023-08-14 and 2024-04-14
* Number of feedbacks NATIVE between 2023-08-14 and 2024-04-14
* Number of feedbacks WEB between 2023-01-14 and 2023-08-14
* Number of feedbacks NATIVE between 2023-01-14 2023-08-14

**Comment by steffenkleinle** [comment]
So the change happened around beginning of August for web and mid August for native. What we did:
* Native: Remove the feedback smileys and move the feedback to the overflow menu
* Web: Merge the two feedback smileys in the toolbar to one "comment" toolbar item

It would be cool to have numbers if one or both led to decreasing feedback numbers before just changing stuff because of assumptions.

**Comment by dkehne** [comment]
@svenseeberg could you maybe deliver the numbers here if there was a change in feedback in that timeframe relatively to a comparable time frame before where we had the smileys or is that already a task for rene/infra issue?

**Comment by clarabracklo** [comment]
There has also been a discussion here about the comparibility of the timeframes before and after the change: https://chat.tuerantuer.org/digitalfabrik/pl/5qp3a1zpktyd5fbuo6hfz7p6ha

**Comment by dkehne** [comment]
From April to July 2023: 856
After the change from August to December 2023: 243

This really fits in the statements from Munich, who said that they have heavily received less feedback and that makes it more difficult for them to improve the content.

Therefore i would suggest to follow @steffenkleinle : "The easiest and most sure way to get users to send feedback would be to display a footer on every page again with feedback." For me it's primary a todo for native, where we moved it into the overflow menu.

Maybe it would be a good idea to add a footer menu on native? We could display the feedback-icon and the sharing-icon there and remove both from the overflow menu so that both functions are also usable independent from the system language?

**Comment by steffenkleinle** [comment]
> From April to July 2023: 856 After the change from August to December 2023: 243
> 
> This really fits in the statements from Munich, who said that they have heavily received less feedback and that makes it more difficult for them to improve the content.

Yes, I think we agree that it got less feedback, I think would still be cool to have separate numbers for web and native to out rule external factors and also to decide whether the change in web removing the two smileys in favor of the one comment icon had a negative effect as well.

> 
> Therefore i would suggest to follow @steffenkleinle : "The easiest and most sure way to get users to send feedback would be to display a footer on every page again with feedback." For me it's primary a todo for native, where we moved it into the overflow menu.
> 
> Maybe it would be a good idea to add a footer menu on native? We could display the feedback-icon and the sharing-icon there and remove both from the overflow menu so that both functions are also usable independent from the system language?

So basically aligning the native app to the mobile web view, i.e. something similar to the screenshot?
![image](https://github.com/digitalfabrik/integreat-app/assets/29095487/2df1cc79-0c7d-47a7-b6ef-7d6bfbab8152)

**Comment by nikolahoff** [comment]
FYI: The last user testing in the café showed the following results regarding finding the feedback function: 13 of 17 were able to send a feedback. @clarabracklo @steffenkleinle

**Comment by hauf-toni** [comment]
Proposal for the new/old/misch-masch =) Feedback function can be found [📍here ](https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=3708-16025&t=fOpnmP8z5EWHKbQX-1)
