### ISSUE TITLE
Weekly and monthly recurring events are sometimes off by one day

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-app#2880]
### Describe the Bug

See https://github.com/digitalfabrik/integreat-cms/issues/2988

### Steps to Reproduce

1. Go to https://admin.integreat-app.de/testumgebung/events/de/6252/edit/
2. See that the date is set to thursday Aug 15th
3. Go to https://integreat.app/testumgebung/de/events/jeden-donnerstag
4. See dates set to be 16th and then every week

### Expected Behavior

Date in the app should be date set in the cms

### Actual Behavior

Date in the app is +1

### Additional Information

https://github.com/digitalfabrik/integreat-cms/issues/2988#issuecomment-2285938397

**Comment by LeandraH** [comment]
Looks so far like this happens when the start day is during summer time, and the start time is before 2 am, including all-day events. The offset during summer time in the German time zone is 2 hours, we're deducting and re-adding those 2 hours because our rrule package doesn't support time zones. I assume the deducting of 2 hours puts us on the previous day and for reasons that I haven't figured out yet, adding the 2 hours back in doesn't put us back on the correct day.

**Comment by LeandraH** [comment]
The problem is that deducting the 2 hours puts us on the previous day, then rrule tells us which day is the next one based on that time, but then we add the 2 hours back in and that can shift us to the next day.
Example: We have an event with starting day 14.8.2024 at 0:00, in UTC that is 13.8.2024 at 22:00. We now want to have the next Friday from rrule, that is 16.8.2024 at 22:00. In Berlin time, that is 17.8.2024 at 0:00, i.e. the Saturday instead of the Friday.
