### ISSUE TITLE
Wickede-Wimbern can't be loaded

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-app#2927]
### Describe the Bug

When changing location in Malte to Wickede-Wimbern error 'request could not be processed' occurs.
(Maybe an CMS erroro?)
### Steps to Reproduce

1. Change location to Wickede-Wimbern
2. See error

### Additional Information

<details>
![image](https://github.com/user-attachments/assets/fc33c47f-a4f1-4c22-8ca0-2ce913801a58)
![image](https://github.com/user-attachments/assets/1f13147f-d0f2-4c63-b7eb-ef4ab2fefdba)

</details>

**Comment by steffenkleinle** [comment]
Wickede-Wimbern is one of the malte facilities that should be only accessible from the local WiFi and therefore is secured by an IP filter. Therefore this is not a bug but instead expected behavior.
@Docmale if you open the developer console and check the requests, they fail with 403 Forbidden errors. If that is the case, this is usually the culprit.

However, the facility should probably not visible in the city selection list. I opened a discussion for this in mattermost.
